name: CI

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'releases/*'
  pull_request:
    branches:
      - 'master'

env:
  DOCKER_IMAGE: oanhnn/ngrok

jobs:
  test:
    name: Check coding style and run phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get verndor
        run: composer install

      - name: Check coding style
        run: composer run cs-check

      - name: Run PHPUnit
        run: composer run test
