name: CI

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'releases/*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  # check-sercurity:
  #   name: '[PHP] Check security'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #     - name: Setting up PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: 7.4
  #         extensions: curl, json
  #         tools: symfony
  #     - name: Run check security
  #       run: symfony security:check

  check-coding-style:
    name: '[PHP] Check coding style'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setting up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: phpcs
      - name: Check coding style
        run: phpcs --standard=phpcs.xml.dist

  run-test:
    name: '[PHP] Test PHP${{ matrix.php }} ${{ matrix.COMPOSER_ARGS }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.2
          - 7.3
          - 7.4
        COMPOSER_ARGS:
          - --prefer-lowest
          - --prefer-stable
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setting up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, json
          coverage: pcov
          ini-values: pcov.directory=src
          tools: composer
      - name: Check PHP
        run: |
          php -v
          php -m
          composer -v
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependencies
        run: composer update --no-interaction --no-suggest --prefer-dist ${{ matrix.COMPOSER_ARGS }}
      - name: Run tests
        run: php -d pcov.enabled=1 vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
      - name: Update test coverage
        if: matrix.php == '7.4' && contains(matrix.COMPOSER_ARGS, 'stable')
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls
          php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
